### ISSUE TITLE
Adding basis vector to multivector changes multivector

### ISSUE THREAD

**Issue by karlwessel** [chakravala/Grassmann.jl#16]
When I add two multivectors `A` and `B` everything works like expected:
```
julia> using Grassmann

julia> @basis "2"
(⟨++⟩, v, v₁, v₂, v₁₂)

julia> A = 2v1 + v2
2v₁ + 1v₂

julia> B = v1 + v2
1v₁ + 1v₂

julia> A + B
3v₁ + 2v₂

julia> A
2v₁ + 1v₂

julia> B
1v₁ + 1v₂
```

However when I add one of the basis vectors (`v1` or `v2`) that are not orthogonal to the multivector, it changes the multivector:
```
julia> v1 + A
3v₁ + 1v₂

julia> A
3v₁ + 1v₂

julia> v1 + A
4v₁ + 1v₂

julia> v1 + A
5v₁ + 1v₂
```

**Comment by chakravala** [comment]
Alright, I have fixed the bug on `master` branch, looks like I forgot to add the `copy` command after making some other changes to my code recently when I introduced the `bcast` method to my code.

This will be released as part of v0.1.6 in the near future, after adding some more changes.

Also, I recommend `basis"2"` over `@basis "2"` if you are using a string.

**Comment by karlwessel** [comment]
> Alright, I have fixed the bug, looks like I forgot to add the `copy` command after making some other changes to my code recently when I introduced the `bcast` method to my code.

Works now, thanks for the quick fix!
> Also, I recommend `basis"2"` over `@basis "2"` if you are using a string.

Ok, will do. I took that kind of style from your [runtests.jl](https://github.com/chakravala/Grassmann.jl/blob/master/test/runtests.jl)

**Comment by karlwessel** [comment]
It seems like the problem is not completely fixed yet, since i get the same problem when adding an `MBlade` to a `MultiVector`:
```
julia> using Grassmann

julia> basis"2"
(⟨++⟩, v, v₁, v₂, v₁₂)

julia> a = v1 + v2
1v₁ + 1v₂

julia> A = v + v1
1 + 1v₁

julia> typeof(a)
MBlade{Int64,⟨++⟩,1,2}

julia> typeof(A)
MultiVector{Int64,⟨++⟩,4}

julia> a+A
1 + 2v₁ + 1v₂

julia> a+A
1 + 3v₁ + 2v₂
```

**Comment by karlwessel** [comment]
Now everything works, thanks again!
